### ISSUE TITLE
Consult about PFDD compilation

### ISSUE THREAD

**Issue by JieLi-HUST** [lanl/Phase-Field-Dislocation-Dynamics-PFDD-2.x#1]

**Comment by akhtar07** [comment]
Request for Documentation and Installation Instructions for PFDD 2.x

I have encountered challenges in accessing adequate documentation or installation instructions for the PFDD 2.x code. Despite its availability as an open-source tool, I have been unable to find comprehensive guidance on how to effectively use or install PFDD for my research purposes. I am reaching out to kindly inquire if you could provide me with some guidance or resources regarding the documentation and installation process for PFDD. Any insights or instructions you could offer would be immensely valuable in helping me utilize PFDD effectively for my research endeavors.

I understand that your time is precious, and I truly appreciate any assistance or direction you can provide on this matter. Your guidance would not only benefit my research but also contribute to advancing the broader understanding and application of PFDD in the scientific community.
